name: "TOML linter"
description: "Lint all your TOML files"
author: "yisonPylkita"
inputs:
  path:
    description: 'Execute lint check on a specific file or folder.'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
branding:
  icon: 'check-circle'
  color: 'green'
