# TODO: write some tests

# name: CI

# env:
#   CARGO_TERM_COLOR: always

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout sources
#       - uses: actions/checkout@v2

#       - name: Run tests
#         run: ./tests/test_runner
#         shell: bash

